---
title: "Flujo_Trabajo_FaunaScope"
author: "Juan Carlos Ramirez Gil"
date: "2025-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduccion

Este código corresponde a u análisis estadístico de la diversidad par aves y mamíferos en la parte alta de cuenca del rio zulia en el departamento de norte de Santander como parte de una prestacion de servicios profesionales en Biologia (Fauna), el siguiente código integra Python desde R Studio para crear un código de análisis reproducible y moderno que permita ahorrar el trabajo de análisis en proyectos futuros.

## Crear repositorio en GitHub para guardar el proyecto

El proyecto sera guardado en un repositorio de github para poder darle trazabilidad al mismo y compartirlo libremente



# Analisis de datos
Se lee el archivo con los registros y los datos ecológicos desde un xlsx en el ordenador donde se realiza el análisis

Hay que recordar que se trabajara desde python, utilizando pandas y leyendo archivos xlsx, para esto se aplica el paquete reticulate para trbajar python desde r studio.


## Ver tabla de registros

# Metodologia


A continuación, se describen los análisis realizados sobre la información obtenida durante el muestreo de fauna.
Riqueza de especies.

Para el presente estudio, la diversidad o riqueza de especies es definida como el número de especies en la zona de estudio, de este modo, y con el fin de hacer una determinación gráfica, se discriminó la totalidad de especies registrados en jerarquías taxonómicas (Orden, Familia, Género, Especie), con el objetivo de identificar el grado de representatividad de cada una.

## Esfuerzo de Muestreo
El esfuerzo de muestreo (E) se estimó de acuerdo con la metodología empleada y las características del grupo taxonómico evaluado, considerando la relación entre el número de unidades de muestreo, el tiempo efectivo de muestreo y, cuando aplicó, el número de observadores o dispositivos utilizados. En términos generales, el esfuerzo se calculó multiplicando el número de unidades de muestreo (trampas, redes, cámaras, transectos o puntos de observación) por el tiempo de exposición o duración de cada sesión de muestreo (horas, días o noches), ajustado al número de personas o equipos activos en campo. Esta aproximación permite estandarizar la intensidad del muestreo entre diferentes métodos y grupos biológicos, facilitando la comparación de resultados y la estimación del éxito de muestreo (Em), definido como la razón entre el número total de registros obtenidos y el esfuerzo total aplicado para cada técnica.




#### Dar Formato a la tabla exportada



## Tabla general grupo taxonomico
La tabla presenta la composición taxonómica y ecológica de las especies registradas durante el muestreo, organizadas jerárquicamente por orden, familia y especie, e incluyendo el nombre común correspondiente. Para cada especie se indica su gremio trófico, lo que permite identificar los principales grupos funcionales presentes en el área de estudio y su papel dentro de la comunidad biológica. Asimismo, se especifican las coberturas o tipos de hábitat en las que fueron registradas, el valor de abundancia relativa o número de individuos observados, y el tipo de registro obtenido (observación directa, captura, fotografía, vocalización, entre otros). Esta información permite evaluar la diversidad, la estructura trófica y el grado de representatividad de las especies en las distintas coberturas evaluadas.





#### Dar Formato a la tabla exportada



## Figura de Ordenes_Familias
La figura muestra la representatividad taxonómica de las especies registradas en el área de estudio, organizadas según su distribución por órdenes y familias. Se observa la variación en el número de especies por familia dentro de cada orden, lo que permite identificar los grupos con mayor riqueza y contribución a la diversidad total. Este tipo de representación facilita visualizar la estructura taxonómica de la comunidad y resalta los patrones de dominancia o equidad entre familias, proporcionando una base para analizar la composición y diversidad biológica del área evaluada.




## Curvas de acumulación de especies
En general, para evaluar la representatividad de los muestreos, se empleó la curva de acumulación de especies para cada una de las coberturas muestreadas, que representa el número de especies acumulado en el inventario frente al esfuerzo de muestreo realizado. De esta manera, la curva de acumulación es la representación gráfica de la cantidad de las especies que van apareciendo en el muestreo. Los cálculos se realizaron utilizando R Studio y Python, disponible en línea. Para determinar la eficiencia de estos muestreos, se utilizaron los estimadores como ACE, Chao de primer orden, Jacknife 1 o Bootstrap, los cuales arrojan resultados más precisos al estimar la riqueza de ensamblajes con gran cantidad de especies “raras".


# Diversidad alfa
Para este análisis se utilizó R Studio y Python con el fin de realiza los análisis de dominancia de Simpson, equitatividad de Pielou y diversidad de Shannon), los cuales nos indican la diversidad de especies de una comunidad particular a la que consideramos homogénea.

## Índice de Simpson (Ds)
Expresa la probabilidad de extraer de la comunidad dos (2) individuos capturados al azar que pertenezcan a la misma especie. Es una medida de cuan dominante es una especie, de esta manera las especies comunes tiene mucho peso respecto a las especies raras. Oscila entre 0 y (1-1/S.

## Índice de Shannon (H´)
El índice de Shannon-Wiener es uno de los índices de medida más simples y de uso más extenso, que mide el grado promedio de incertidumbre para predecir la especie a la que pertenece un individuo dado, elegido al azar dentro de la comunidad. Mide la variedad de especies de un área determinada, indicando su diversidad y frecuencia; una alta diversidad indica un alto grado de desarrollo y estabilidad de la biota; se basa en la abundancia proporcional de las especies como en su riqueza; se incrementa con el número de especies y el número de individuos.

## Índice de equitatividad de Pielou (J)
El Índice de equitatividad de Pielou (J’) mide la proporción de la diversidad observada con relación a la máxima diversidad esperada. Su valor va de cero a uno de forma que uno corresponde a situaciones donde todas las especies son igualmente abundantes. Esta medida al igual que Shannon considera que todas las especies de la comunidad se han contabilizado en la muestra.

## Curvas rango abundancia
Las curvas rango-abundancia se emplearon para comparar la distribución de la abundancia y la uniformidad de las especies entre las diferentes unidades de muestreo. Este tipo de representación permite visualizar tanto la riqueza específica (a partir de la longitud del eje de rango) como la dominancia o equidad en la abundancia de las especies (según la pendiente de la curva). Para facilitar la interpretación y reducir la asimetría de los datos, los valores de abundancia fueron transformados mediante una escala logarítmica de base 10 (log₁₀), lo que permite representar de manera proporcional las diferencias entre especies comunes y raras. Estas curvas son ampliamente utilizadas en estudios de caracterización y estructura de comunidades biológicas, ya que permiten evaluar la composición y el grado de dominancia de los taxones en los distintos hábitats o coberturas analizadas.

## Uso de habitat
Para el análisis del uso de hábitat, se contabilizó el número total de especies registradas en cada cobertura, así como aquellas consideradas exclusivas, es decir, presentes únicamente en una de ellas. Este enfoque permite identificar la representatividad y afinidad de las especies con cada tipo de hábitat, facilitando la comparación de la riqueza y la singularidad biológica entre unidades de muestreo. Las coberturas con mayor número de especies indican una mayor diversidad estructural y funcional del hábitat, mientras que aquellas con un número elevado de especies exclusivas reflejan condiciones particulares que favorecen la presencia de taxones especializados o con requerimientos ecológicos específicos. En conjunto, este análisis ofrece una visión integral sobre cómo las especies utilizan los distintos ambientes disponibles y permite inferir la importancia relativa de cada cobertura en la conservación de la diversidad local.

## Gremios tróficos
Los gremios tróficos se definieron como omnívoro (consumo de material vegetal, animal y alimentos procesados), Insectívoro (consumo de insectos), Folívoro (consumo de hojas), Granívoro (consumo de granos y semillas), Herbívoro (consumo de vegetales), Hematófagos (consumo de sangre), Frugívoro (consumo de frutos), carnívoro (consumo de carne de otros animales), Nectarívoro (consumo del néctar de las flores), Piscívoro (consumo de peces) y Carroñero (consumo de cadáveres de animales). La caracterización trófica, se realizó en base a los resultados de abundancia relativa, para facilitar la cuantificación de la misma.

# Especies de importancia económica y cultural

## Especies sensibles
Posterior a esto, se evaluaron las especies sensibles, Estas especies se reconocen como todas aquellas que, debido a alguna característica ecológica o poblacional, son más perceptivas al cambio ambiental que producen las actividades antrópicas. A partir de esto, fueron analizadas aquellas especies que han sido catalogadas como amenazadas de extinción, para lo cual se tuvieron en cuenta las categorías establecidas a nivel global por la Unión Internacional para la Conservación de la Naturaleza UICN (2021), y a nivel nacional por la Resolución 0126 de 2024 del MADS. Así mismo, se analizaron aquellas especies que presentan restricción en su comercio a través de la lista de la Convención sobre el Comercio Internacional de Especies Amenazadas de Fauna y Flora Silvestres (CITES), aquellas que tuvieran rangos de distribución muy pequeños o restringidos (endémicas) y las especies con algún patrón de migración dentro del territorio, para lo cual fue evaluado el Plan Nacional de especies Migratorias de Naranjo y Amaya y Naranjo et al.   y la Guía de las especies migratorias de la biodiversidad en Colombia de Amaya-Espinel y Zapata.

### UICN

Siguiendo los criterios establecidos por la Unión Internacional para la Conservación de la naturaleza (IUCN), las categorías de amenaza han sido definidas como:

En Peligro Crítico (CR): en esta categoría se incluyen las especies que enfrentan un riesgo extremadamente alto de extinción en estado silvestre, en el futuro inmediato.

En Peligro (EN): esta categoría incluye las especies que no están en “peligro crítico”, pero están enfrentando un muy alto riesgo de extinción o deterioro poblacional en estado silvestre, en el futuro cercano.

Vulnerables (VU): un taxón está en la categoría de VU, cuando la mejor evidencia disponible indica que enfrenta un moderado riesgo de extinción o deterioro poblacional a mediano plazo.

### CITES

Las especies amparadas por la Convención sobre el Comercio Internacional de Especies Amenazadas de Fauna y Flora Silvestres (CITES), se encuentran incluidas en tres apéndices según el grado de protección que necesiten, los cuales se describen a continuación:

Apéndice I: Incluye todas las especies en peligro de extinción, y el comercio de esas especies se autorizará solamente bajo circunstancias excepcionales. 

Apéndice II: Incluye las especies que no se encuentran necesariamente en peligro de extinción, pero cuyo comercio debe controlarse a fin de evitar una utilización incompatible con su supervivencia. 

Apéndice III: Incluye especies que están protegidas al menos en un país, el cual ha solicitado la asistencia de otras partes de las CITES para controlar su comercio.


Los análisis y gráficos se realizaron con los softwares libres R Studio, Python y una hoja de cálculo de Microsoft Excel. 

